In [2]:
import numpy as np

In [4]:
A = np.array([1,1,1])
B = np.array([2,2,2])
print(A)
print(B)

[1 1 1]
[2 2 2]


vstack，上下合并

In [5]:
C = np.vstack((A,B)) #将A，B上下合并
print(C,C.shape)

[[1 1 1]
 [2 2 2]] (2, 3)


hstack，左右合并

补充一个维度，置于列位

In [6]:
D = np.hstack((A,B)) #将A，B左右合并
print(D,D.shape)

[1 1 1 2 2 2] (6,)


In [7]:
print(A[:,np.newaxis]) #补充一个维度

[[1]
 [1]
 [1]]


补充一个维度，置于行位

In [8]:
print(A[np.newaxis,:]) #补充一个维度

[[1 1 1]]


重新设计为3行1列

In [9]:
print(A.reshape(3,1)) 

[[1]
 [1]
 [1]]


axis=0即上下维度合并

In [8]:
E = np.concatenate((A,B,B,A),axis=0)
print(E)

[1 1 1 2 2 2 2 2 2 1 1 1]


In [11]:
A = np.array([1,1,1])[:,np.newaxis]
B = np.array([2,2,2])[:,np.newaxis]
print(A)
print(B)

[[1]
 [1]
 [1]]
[[2]
 [2]
 [2]]


axis=1即横向维度合并

In [12]:
F = np.concatenate((A,B,B,A),axis=1)
print(F)

[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]
