In [1]:
import numpy as np
a = np.array([1,2,3,4])
b = a #b指向与a相同的一块内存
print(a)
print(b)
print(id(a),id(b))#查看内存地址
b is a

[1 2 3 4]
[1 2 3 4]
2346355772352 2346355772352


True

In [2]:
a[0]=0.3
print(a)

[0 2 3 4]


In [3]:
a[2]=2.8
print(a)

[0 2 2 4]


a 与 b由于代指同一块内存，故同步变化

In [4]:
print(b[1:3])
a[1:3]=[22,33]
print(b)

[2 2]
[ 0 22 33  4]


仅给c赋予a的值

In [5]:
c = a.copy()
a[0]=5
print(c)
print(b)

[ 0 22 33  4]
[ 5 22 33  4]
