In [1]:
import numpy as np

In [2]:
A = np.arange(12).reshape((3,4))
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


按axis=1，纵向分割为2列

In [3]:
print(np.split(A,2,axis=1))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [4]:
print(np.hsplit(A,2))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


按axis=0，横向分割为3行

In [5]:
print(np.split(A,3,axis=0))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [6]:
print(np.vsplit(A,3))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


进行不等量分割1

In [7]:
print(np.split(A,[1,1,2],axis=1))

[array([[0],
       [4],
       [8]]), array([], shape=(3, 0), dtype=int32), array([[1],
       [5],
       [9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


进行不等量分割2

In [8]:
print(np.array_split(A,3,axis=1))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
